USE ventas_jugos;

CREATE TABLE tb_vendedor(
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) DEFAULT NULL,
BARRIO VARCHAR(50) DEFAULT NULL,
COMISION FLOAT DEFAULT NULL,
FECHA_ADMISION DATE DEFAULT NULL,
DE_VACACIONES BIT(1) DEFAULT NULL,
PRIMARY KEY (MATRICULA)
);

CREATE TABLE tb_producto(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100) DEFAULT NULL,
SABOR VARCHAR(50) DEFAULT NULL,
TAMAÑO VARCHAR(50) DEFAULT NULL,
ENVASE VARCHAR(50) DEFAULT NULL,
PRECIO_LISTA FLOAT DEFAULT NULL, 
PRIMARY KEY (CODIGO)
);

CREATE TABLE tb_cliente(
DNI VARCHAR(20) NOT NULL,
NOMBRE VARCHAR(50) DEFAULT NULL,
DIRECCION VARCHAR(100) DEFAULT NULL,
BARRIO VARCHAR(50) DEFAULT NULL,
CIUDAD VARCHAR(15) DEFAULT NULL,
ESTADO VARCHAR(15) DEFAULT NULL,
CP VARCHAR(10) DEFAULT NULL,
FECHA_NACIMIENTO DATE DEFAULT NULL,
EDAD INT DEFAULT NULL,
SEXO VARCHAR(1) DEFAULT NULL,
LIMITE_CREDITO FLOAT DEFAULT NULL,
VOLUMEN_COMPRA FLOAT DEFAULT NULL,
PRIMERA_COMPRA BIT DEFAULT NULL,
PRIMARY KEY (DNI)
);

CREATE TABLE tb_ventas(
NUMERO VARCHAR(10),
FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
DNI VARCHAR(20) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT DEFAULT NULL,
PRIMARY KEY (NUMERO),
FOREIGN KEY (DNI) REFERENCES tb_cliente(DNI),
FOREIGN KEY (MATRICULA) REFERENCES tb_vendedor(MATRICULA)
);
ALTER TABLE tb_ventas RENAME tb_factura; #renombrar la tabla de "tb_ventas"

CREATE TABLE tb_items_facturas(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
CANTIDAD INT DEFAULT NULL,
PRECIO FLOAT DEFAULT NULL,
PRIMARY KEY (NUMERO,CODIGO),
FOREIGN KEY (NUMERO) REFERENCES tb_factura(NUMERO),
FOREIGN KEY (CODIGO) REFERENCES tb_producto(CODIGO)
);





